# DRACULA
gui:
  theme:
    activeBorderColor:
      - "#a2c9fd"
      - bold
    inactiveBorderColor:
      - "#8d9199"

    searchingActiveBorderColor:
      - "#d7bde4"
      - bold

    optionsTextColor:
      - "#c3c6cf"

    selectedLineBgColor:
      - "#37618e"

    inactiveViewSelectedLineBgColor:
      - bold

    cherryPickedCommitFgColor:
      - "#3b2947"

    cherryPickedCommitBgColor:
      - "#d7bde4"

    markedBaseCommitFgColor:
      - "#253141"

    markedBaseCommitBgColor:
      - "#bbc7db"

    unstagedChangesColor:
      - "#ffb4ab"

    defaultFgColor:
      - "#e1e2e8"