# DRACULA
gui:
  theme:
    activeBorderColor:
      - "#d3c972"
      - bold
    inactiveBorderColor:
      - "#959181"

    searchingActiveBorderColor:
      - "#a6d0b8"
      - bold

    optionsTextColor:
      - "#cbc7b5"

    selectedLineBgColor:
      - "#676013"

    inactiveViewSelectedLineBgColor:
      - bold

    cherryPickedCommitFgColor:
      - "#0f3727"

    cherryPickedCommitBgColor:
      - "#a6d0b8"

    markedBaseCommitFgColor:
      - "#343117"

    markedBaseCommitBgColor:
      - "#cdc7a3"

    unstagedChangesColor:
      - "#ffb4ab"

    defaultFgColor:
      - "#e7e2d5"