# DRACULA
gui:
  theme:
    activeBorderColor:
      - "#acc7ff"
      - bold
    inactiveBorderColor:
      - "#8e9099"

    searchingActiveBorderColor:
      - "#ddbce0"
      - bold

    optionsTextColor:
      - "#c4c6d0"

    selectedLineBgColor:
      - "#435e91"

    inactiveViewSelectedLineBgColor:
      - bold

    cherryPickedCommitFgColor:
      - "#3f2844"

    cherryPickedCommitBgColor:
      - "#ddbce0"

    markedBaseCommitFgColor:
      - "#283041"

    markedBaseCommitBgColor:
      - "#bec6dc"

    unstagedChangesColor:
      - "#ffb4ab"

    defaultFgColor:
      - "#e2e2e9"