# DRACULA
gui:
  theme:
    activeBorderColor:
      - "#c8bfff"
      - bold
    inactiveBorderColor:
      - "#928f99"

    searchingActiveBorderColor:
      - "#ecb8ce"
      - bold

    optionsTextColor:
      - "#c9c5d0"

    selectedLineBgColor:
      - "#5e5791"

    inactiveViewSelectedLineBgColor:
      - bold

    cherryPickedCommitFgColor:
      - "#482536"

    cherryPickedCommitBgColor:
      - "#ecb8ce"

    markedBaseCommitFgColor:
      - "#312e41"

    markedBaseCommitBgColor:
      - "#c9c3dc"

    unstagedChangesColor:
      - "#ffb4ab"

    defaultFgColor:
      - "#e5e1e9"