# DRACULA
gui:
  theme:
    activeBorderColor:
      - "#e9c16c"
      - bold
    inactiveBorderColor:
      - "#998f80"

    searchingActiveBorderColor:
      - "#b0cfa9"
      - bold

    optionsTextColor:
      - "#d0c5b4"

    selectedLineBgColor:
      - "#775a0b"

    inactiveViewSelectedLineBgColor:
      - bold

    cherryPickedCommitFgColor:
      - "#1d361c"

    cherryPickedCommitBgColor:
      - "#b0cfa9"

    markedBaseCommitFgColor:
      - "#3b2f15"

    markedBaseCommitBgColor:
      - "#d8c4a0"

    unstagedChangesColor:
      - "#ffb4ab"

    defaultFgColor:
      - "#ebe1d4"