# DRACULA
gui:
  theme:
    activeBorderColor:
      - "#80d4dc"
      - bold
    inactiveBorderColor:
      - "#899393"

    searchingActiveBorderColor:
      - "#b7c7ea"
      - bold

    optionsTextColor:
      - "#bec8c9"

    selectedLineBgColor:
      - "#006970"

    inactiveViewSelectedLineBgColor:
      - bold

    cherryPickedCommitFgColor:
      - "#21304c"

    cherryPickedCommitBgColor:
      - "#b7c7ea"

    markedBaseCommitFgColor:
      - "#1b3437"

    markedBaseCommitBgColor:
      - "#b1cbce"

    unstagedChangesColor:
      - "#ffb4ab"

    defaultFgColor:
      - "#dee4e4"