# DRACULA
gui:
  theme:
    activeBorderColor:
      - "#bac3ff"
      - bold
    inactiveBorderColor:
      - "#90909a"

    searchingActiveBorderColor:
      - "#e5bad7"
      - bold

    optionsTextColor:
      - "#c7c5d0"

    selectedLineBgColor:
      - "#515b92"

    inactiveViewSelectedLineBgColor:
      - bold

    cherryPickedCommitFgColor:
      - "#44263d"

    cherryPickedCommitBgColor:
      - "#e5bad7"

    markedBaseCommitFgColor:
      - "#2d2f42"

    markedBaseCommitBgColor:
      - "#c3c5dd"

    unstagedChangesColor:
      - "#ffb4ab"

    defaultFgColor:
      - "#e4e1e9"