# DRACULA
gui:
  theme:
    activeBorderColor:
      - "#ffb2be"
      - bold
    inactiveBorderColor:
      - "#9f8c8e"

    searchingActiveBorderColor:
      - "#ebbf90"
      - bold

    optionsTextColor:
      - "#d6c2c3"

    selectedLineBgColor:
      - "#8e4957"

    inactiveViewSelectedLineBgColor:
      - bold

    cherryPickedCommitFgColor:
      - "#452b08"

    cherryPickedCommitBgColor:
      - "#ebbf90"

    markedBaseCommitFgColor:
      - "#43292e"

    markedBaseCommitBgColor:
      - "#e4bdc2"

    unstagedChangesColor:
      - "#ffb4ab"

    defaultFgColor:
      - "#f0dee0"