# DRACULA
gui:
  theme:
    activeBorderColor:
      - "#9ccbfb"
      - bold
    inactiveBorderColor:
      - "#8c9199"

    searchingActiveBorderColor:
      - "#d4bee6"
      - bold

    optionsTextColor:
      - "#c2c7cf"

    selectedLineBgColor:
      - "#31628d"

    inactiveViewSelectedLineBgColor:
      - bold

    cherryPickedCommitFgColor:
      - "#392a49"

    cherryPickedCommitBgColor:
      - "#d4bee6"

    markedBaseCommitFgColor:
      - "#243240"

    markedBaseCommitBgColor:
      - "#b9c8da"

    unstagedChangesColor:
      - "#ffb4ab"

    defaultFgColor:
      - "#e0e2e8"