# DRACULA
gui:
  theme:
    activeBorderColor:
      - "#ffb4a8"
      - bold
    inactiveBorderColor:
      - "#a08c89"

    searchingActiveBorderColor:
      - "#dec48c"
      - bold

    optionsTextColor:
      - "#d8c2be"

    selectedLineBgColor:
      - "#904b40"

    inactiveViewSelectedLineBgColor:
      - bold

    cherryPickedCommitFgColor:
      - "#3e2e04"

    cherryPickedCommitBgColor:
      - "#dec48c"

    markedBaseCommitFgColor:
      - "#442925"

    markedBaseCommitBgColor:
      - "#e7bdb6"

    unstagedChangesColor:
      - "#ffb4ab"

    defaultFgColor:
      - "#f1dfdc"